---
- name: Create configuration directory
  hosts: localhost
  gather_facts: no
  tasks:
    - file: path=./configs state=absent
      run_once: true
    - file: path=./configs state=directory
      run_once: true
- name: Create configuration files
  hosts: all
  gather_facts: no
  tasks:     
    - template: src="{{ansible_device_type}}.j2" dest="./configs/{{inventory_hostname}}.txt"



