---
snmp_server: 10.10.10.10
syslog_server: 10.10.10.10
eos_provider:
  username:  "{{ansible_user}}"
  password:  "{{ansible_ssh_pass}}"
  host:      "{{ip|default(ansible_host)|default(inventory_hostname)}}"
  transport: eapi
  use_ssl: true
  validate_certs: False
ios_provider:
  username:  "{{ansible_user}}"
  password:  "{{ansible_ssh_pass}}"
  host:      "{{ip|default(ansible_host)|default(inventory_hostname)}}"
  transport: cli