---
ansible_device_os: ios
snmp_community: cisco
ios_provider:
  username:  "{{ansible_user}}"
  password:  "{{ansible_ssh_pass}}"
  host:      "{{ip|default(ansible_host)|default(inventory_hostname)}}"
  transport: cli