---
- name: Check if SNMP is correctly configured in WAN Routers
  hosts: WAN_Router
  gather_facts: no
  vars_files: 
    - ./passwords.yml
  tasks: 
    - ios_command:
        provider: "{{ios_provider}}"
        commands: "show snmp community"
      register: result
    - set_fact: json_result="{{result.stdout[0]}}"
    - debug: var=json_result
    - set_fact: error_no_community=0
    - set_fact: error_no_community=1
      when: "not('name: '~snmp_community in result.stdout[0])"
    - debug: var=error_no_community

- name: Check if SNMP is correctly configured in DC Spines
  hosts: SPINE
  gather_facts: no
  vars_files: 
    - ./passwords.yml
  tasks: 
    - eos_facts:
        provider: "{{eos_provider}}"
        gather_subset: config
    - debug: var=ansible_net_config