---
- name: Check if SNMP is configured
  hosts: WAN_Router
  gather_facts: no
  vars_files: 
    - ./passwords.yml
  tasks: 
    - ios_command:
        commands: "show snmp community"
      register: result
    - set_fact: json_result="{{result.stdout[0]}}"
    - debug: var=json_result
    - set_fact: error_no_community=1
      when: "not('name: '~snmp_community in result.stdout[0])"